// <auto-generated />
using System;
using CoreAppwithSSO.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreAppwithSSO.API.Migrations.Sso
{
    [DbContext(typeof(SsoDbContext))]
    [Migration("20260527091822_UpdateAppBaseUrlsToIis")]
    partial class UpdateAppBaseUrlsToIis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreAppwithSSO.API.Models.Sso.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "http://localhost:8081/hr/",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Human Resources Management",
                            DisplayOrder = 1,
                            IconColor = "#4285F4",
                            IconName = "people",
                            IsActive = true,
                            Name = "HR Portal"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "http://localhost:8081/finance/",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Financial Management System",
                            DisplayOrder = 2,
                            IconColor = "#EA4335",
                            IconName = "account_balance",
                            IsActive = true,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://projects.yourcompany.com",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Project Management Tool",
                            DisplayOrder = 3,
                            IconColor = "#FBBC05",
                            IconName = "assignment",
                            IsActive = true,
                            Name = "Project Mgmt"
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://crm.yourcompany.com",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customer Relationship Management",
                            DisplayOrder = 4,
                            IconColor = "#34A853",
                            IconName = "contacts",
                            IsActive = true,
                            Name = "CRM"
                        },
                        new
                        {
                            Id = 5,
                            BaseUrl = "http://localhost:8081/inventory/",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Inventory Management System",
                            DisplayOrder = 5,
                            IconColor = "#FF6D01",
                            IconName = "inventory_2",
                            IsActive = true,
                            Name = "Inventory"
                        },
                        new
                        {
                            Id = 6,
                            BaseUrl = "https://reports.yourcompany.com",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Business Intelligence & Reports",
                            DisplayOrder = 6,
                            IconColor = "#46BDC6",
                            IconName = "analytics",
                            IsActive = true,
                            Name = "Reports"
                        },
                        new
                        {
                            Id = 7,
                            BaseUrl = "https://mail.yourcompany.com",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Corporate Email System",
                            DisplayOrder = 7,
                            IconColor = "#7B1FA2",
                            IconName = "email",
                            IsActive = true,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 8,
                            BaseUrl = "https://calendar.yourcompany.com",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Team Calendar & Scheduling",
                            DisplayOrder = 8,
                            IconColor = "#0097A7",
                            IconName = "calendar_month",
                            IsActive = true,
                            Name = "Calendar"
                        },
                        new
                        {
                            Id = 9,
                            BaseUrl = "https://admin.yourcompany.com",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System Administration",
                            DisplayOrder = 9,
                            IconColor = "#616161",
                            IconName = "admin_panel_settings",
                            IsActive = true,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("CoreAppwithSSO.API.Models.Sso.SsoToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("SsoTokens");
                });

            modelBuilder.Entity("CoreAppwithSSO.API.Models.Sso.TenantApplication", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("TenantId", "ApplicationId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("TenantApplications");
                });

            modelBuilder.Entity("CoreAppwithSSO.API.Models.Sso.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SsoTokenId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SsoTokenId");

                    b.HasIndex("UserId", "TenantId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("CoreAppwithSSO.API.Models.Sso.SsoToken", b =>
                {
                    b.HasOne("CoreAppwithSSO.API.Models.Sso.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("CoreAppwithSSO.API.Models.Sso.TenantApplication", b =>
                {
                    b.HasOne("CoreAppwithSSO.API.Models.Sso.Application", "Application")
                        .WithMany("TenantApplications")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("CoreAppwithSSO.API.Models.Sso.UserSession", b =>
                {
                    b.HasOne("CoreAppwithSSO.API.Models.Sso.SsoToken", "SsoToken")
                        .WithMany()
                        .HasForeignKey("SsoTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SsoToken");
                });

            modelBuilder.Entity("CoreAppwithSSO.API.Models.Sso.Application", b =>
                {
                    b.Navigation("TenantApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
